### ISSUE TITLE
Adding sqlfmt formatting

### ISSUE THREAD

**Issue by ran-eh** [shinichi-takii/vscode-language-sql-bigquery#11]
Hi!  I love this extension - thanks!

One way to make it better is to also add formatting - currently when I try to format it says that no formatting is configured for this language.  Would you consider adding formatting - perhaps sqlfmt?  I would have looked into it myself, but have not written vscode extensions before, and am swamped with work.  Thanks!

-- Ran

**Comment by shinichi-takii** [comment]
Thank you for using.

It's no plans to implement. Sorry.

I recommend [SQL Formatter Mod](https://marketplace.visualstudio.com/items?itemName=nmrmsys.vscode-sql-formatter-mod) of VS Code Extension.  
If you like, please use [SQL Formatter Mod](https://marketplace.visualstudio.com/items?itemName=nmrmsys.vscode-sql-formatter-mod).

Regards.

**Comment by ran-eh** [comment]
Thanks - will try!

**Comment by shinichi-takii** [comment]
@ran-eh 
Thank you for the reply.

I close this issue.

Thanks.
