### ISSUE TITLE
Change default saved file extension to .sql

### ISSUE THREAD

**Issue by sethshenbanjo** [shinichi-takii/vscode-language-sql-bigquery#12]
### Description

Change default saved file extension to .sql - currently it's .dml, is there a way to change this please?

**Comment by shinichi-takii** [comment]
@sethshenbanjo 
Hello Seth,

This extension package doesn't set a default save file extension.
and, default saved file extension is `.sql` in my VSCode.

Please check any settings in your VSCode.

Thank you.

**Comment by sethshenbanjo** [comment]
I see thanks very much - I’ll double check!

On 29 Feb 2020, at 02:12, Shinichi Takii <notifications@github.com> wrote:

﻿

@sethshenbanjo<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsethshenbanjo&data=02%7C01%7C%7C95906567748240dcddca08d7bcbccafb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637185391346313599&sdata=B%2FPu1T6vH8yjS9F0z6pPrNudeI8dzXJ4ouiu4SdHHhM%3D&reserved=0>
Hello Seth,

This extension package doesn't set a default save file extension.
and, default saved file extension is .sql in my VSCode.

Please check any settings in your VSCode.

Thank you.

**Comment by shinichi-takii** [comment]
@sethshenbanjo 
Thank you for reply.

I close this issue.

Thanks.
