### ISSUE TITLE
Default comment/uncomment option

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [shinichi-takii/vscode-language-sql-bigquery#15]
### Description
BigQuery UI switched from -- to # default line commenting option
It will be nice if the BigQuery visual code follows the same.

### Additional Information

Example copy and paste code BigQuery
```SQL
SELECT
[1,
# 2,
3] AS numbers
```

I try to uncomment row 3 in visual code, will create a new commenting using another symbol.
```SQL
SELECT
[1,
-- # 2, 
3] AS numbers
```

**Comment by shinichi-takii** [comment]
@VelizarVESSELINOV 
Changed **single line comment symbol** from `--` to `#`.
Please update the extension to `v1.5.0`.

Thanks.
